-- Autogenerated by CIL2Ada v. 2
with MSSyst.Object;
with CIL_Types;
use CIL_Types;
limited with Microsoft.VisualStudio.OLE.Interop.IOleUndoManager;
with MSSyst.Guid;
limited with MSSyst.String;
package Microsoft.VisualStudio.TextManager.Interop.IVsTextBuffer is
   type Typ is interface;
   type Ref is access all Typ'Class;
   type Ref_addrof is access all Ref;
   type Ref_Arr is array (Natural range <>) of Ref;
   type Ref_Array is access all Ref_Arr;
   type Ref_Array_addrof is access all Ref_Array;
   function GetLanguageServiceID
     (This : access Typ;
      pguidLangService : access MSSyst.Guid.Valuetype) return Integer is abstract;
   function GetLastLineIndex
     (This : access Typ;
      piLine : CIL_Types.Int32_addrof;
      piIndex : CIL_Types.Int32_addrof) return Integer is abstract;
   function GetLengthOfLine
     (This : access Typ;
      iLine : Integer;
      piLength : CIL_Types.Int32_addrof) return Integer is abstract;
   function GetLineCount
     (This : access Typ;
      piLineCount : CIL_Types.Int32_addrof) return Integer is abstract;
   function GetLineIndexOfPosition
     (This : access Typ;
      iPosition : Integer;
      piLine : CIL_Types.Int32_addrof;
      piColumn : CIL_Types.Int32_addrof) return Integer is abstract;
   function GetPositionOfLine
     (This : access Typ;
      iLine : Integer;
      piPosition : CIL_Types.Int32_addrof) return Integer is abstract;
   function GetPositionOfLineIndex
     (This : access Typ;
      iLine : Integer;
      iIndex : Integer;
      piPosition : CIL_Types.Int32_addrof) return Integer is abstract;
   function GetSize
     (This : access Typ;
      piLength : CIL_Types.Int32_addrof) return Integer is abstract;
   function GetStateFlags
     (This : access Typ;
      pdwReadOnlyFlags : CIL_Types.Unsigned_Integer_addrof) return Integer is abstract;
   function GetUndoManager
     (This : access Typ;
      ppUndoManager : access Microsoft.VisualStudio.OLE.Interop.IOleUndoManager.Ref) return Integer is abstract;
   function InitializeContent
     (This : access Typ;
      pszText : access MSSyst.String.Typ'Class;
      iLength : Integer) return Integer is abstract;
   function LockBuffer
     (This : access Typ) return Integer is abstract;
   function LockBufferEx
     (This : access Typ;
      dwFlags : CIL_Types.Unsigned_Integer) return Integer is abstract;
   function Reload
     (This : access Typ;
      fUndoable : Integer) return Integer is abstract;
   function Reserved1
     (This : access Typ) return Integer is abstract;
   function Reserved10
     (This : access Typ) return Integer is abstract;
   function Reserved2
     (This : access Typ) return Integer is abstract;
   function Reserved3
     (This : access Typ) return Integer is abstract;
   function Reserved4
     (This : access Typ) return Integer is abstract;
   function Reserved5
     (This : access Typ) return Integer is abstract;
   function Reserved6
     (This : access Typ) return Integer is abstract;
   function Reserved7
     (This : access Typ) return Integer is abstract;
   function Reserved8
     (This : access Typ) return Integer is abstract;
   function Reserved9
     (This : access Typ) return Integer is abstract;
   function SetLanguageServiceID
     (This : access Typ;
      guidLangService : access MSSyst.Guid.Valuetype) return Integer is abstract;
   function SetStateFlags
     (This : access Typ;
      dwReadOnlyFlags : CIL_Types.Unsigned_Integer) return Integer is abstract;
   function UnlockBuffer
     (This : access Typ) return Integer is abstract;
   function UnlockBufferEx
     (This : access Typ;
      dwFlags : CIL_Types.Unsigned_Integer) return Integer is abstract;
private
   pragma Import (CIL, GetLanguageServiceID, "GetLanguageServiceID");
   pragma Import (CIL, GetLastLineIndex, "GetLastLineIndex");
   pragma Import (CIL, GetLengthOfLine, "GetLengthOfLine");
   pragma Import (CIL, GetLineCount, "GetLineCount");
   pragma Import (CIL, GetLineIndexOfPosition, "GetLineIndexOfPosition");
   pragma Import (CIL, GetPositionOfLine, "GetPositionOfLine");
   pragma Import (CIL, GetPositionOfLineIndex, "GetPositionOfLineIndex");
   pragma Import (CIL, GetSize, "GetSize");
   pragma Import (CIL, GetStateFlags, "GetStateFlags");
   pragma Import (CIL, GetUndoManager, "GetUndoManager");
   pragma Import (CIL, InitializeContent, "InitializeContent");
   pragma Import (CIL, LockBuffer, "LockBuffer");
   pragma Import (CIL, LockBufferEx, "LockBufferEx");
   pragma Import (CIL, Reload, "Reload");
   pragma Import (CIL, Reserved1, "Reserved1");
   pragma Import (CIL, Reserved10, "Reserved10");
   pragma Import (CIL, Reserved2, "Reserved2");
   pragma Import (CIL, Reserved3, "Reserved3");
   pragma Import (CIL, Reserved4, "Reserved4");
   pragma Import (CIL, Reserved5, "Reserved5");
   pragma Import (CIL, Reserved6, "Reserved6");
   pragma Import (CIL, Reserved7, "Reserved7");
   pragma Import (CIL, Reserved8, "Reserved8");
   pragma Import (CIL, Reserved9, "Reserved9");
   pragma Import (CIL, SetLanguageServiceID, "SetLanguageServiceID");
   pragma Import (CIL, SetStateFlags, "SetStateFlags");
   pragma Import (CIL, UnlockBuffer, "UnlockBuffer");
   pragma Import (CIL, UnlockBufferEx, "UnlockBufferEx");
end Microsoft.VisualStudio.TextManager.Interop.IVsTextBuffer;
pragma Import (CIL, Microsoft.VisualStudio.TextManager.Interop.IVsTextBuffer,
   ".ver 7:1:40304:0 .publickeytoken=( b0 3f 5f 7f 11 d5 0a 3a )",
   "[Microsoft.VisualStudio.TextManager.Interop]Microsoft.VisualStudio.TextManager.Interop.IVsTextBuffer");
