-- Autogenerated by CIL2Ada v. 2
with MSSyst.Object;
with CIL_Types;
use CIL_Types;
with Microsoft.VisualStudio.OLE.Interop.RECT;
with Microsoft.VisualStudio.TextManager.Interop.TIPSIZEDATA;
package Microsoft.VisualStudio.TextManager.Interop.IVsTipWindow is
   type Typ is interface;
   type Ref is access all Typ'Class;
   type Ref_addrof is access all Ref;
   type Ref_Arr is array (Natural range <>) of Ref;
   type Ref_Array is access all Ref_Arr;
   type Ref_Array_addrof is access all Ref_Array;
   procedure Dismiss
     (This : access Typ) is abstract;
   function GetContextStream
     (This : access Typ;
      piPos : CIL_Types.Int32_addrof;
      piLength : CIL_Types.Int32_addrof) return Integer is abstract;
   function GetSizePreferences
     (This : access Typ;
      prcCtxBounds : access Microsoft.VisualStudio.OLE.Interop.RECT.Valuetype_arr;
      pSizeData : access Microsoft.VisualStudio.TextManager.Interop.TIPSIZEDATA.Valuetype_arr) return Integer is abstract;
   function Paint
     (This : access Typ;
      hdc : CIL_Types.native_int;
      prc : access Microsoft.VisualStudio.OLE.Interop.RECT.Valuetype_arr) return Integer is abstract;
   function WndProc
     (This : access Typ;
      hwnd : CIL_Types.native_int;
      iMsg : CIL_Types.Unsigned_Integer;
      wParam : CIL_Types.native_int;
      lParam : CIL_Types.native_int) return Integer is abstract;
private
   pragma Import (CIL, Dismiss, "Dismiss");
   pragma Import (CIL, GetContextStream, "GetContextStream");
   pragma Import (CIL, GetSizePreferences, "GetSizePreferences");
   pragma Import (CIL, Paint, "Paint");
   pragma Import (CIL, WndProc, "WndProc");
end Microsoft.VisualStudio.TextManager.Interop.IVsTipWindow;
pragma Import (CIL, Microsoft.VisualStudio.TextManager.Interop.IVsTipWindow,
   ".ver 7:1:40304:0 .publickeytoken=( b0 3f 5f 7f 11 d5 0a 3a )",
   "[Microsoft.VisualStudio.TextManager.Interop]Microsoft.VisualStudio.TextManager.Interop.IVsTipWindow");
