-- Autogenerated by CIL2Ada v. 2
with MSSyst.Object;
with CIL_Types;
use CIL_Types;
with Microsoft.VisualStudio.OLE.Interop.BIND_OPTS2;
limited with Microsoft.VisualStudio.OLE.Interop.IEnumString;
limited with Microsoft.VisualStudio.OLE.Interop.IRunningObjectTable;
limited with MSSyst.String;
package Microsoft.VisualStudio.OLE.Interop.IBindCtx is
   type Typ is interface;
   type Ref is access all Typ'Class;
   type Ref_addrof is access all Ref;
   type Ref_Arr is array (Natural range <>) of Ref;
   type Ref_Array is access all Ref_Arr;
   type Ref_Array_addrof is access all Ref_Array;
   procedure EnumObjectParam
     (This : access Typ;
      ppEnum : access Microsoft.VisualStudio.OLE.Interop.IEnumString.Ref) is abstract;
   procedure GetBindOptions
     (This : access Typ;
      pbindopts : access Microsoft.VisualStudio.OLE.Interop.BIND_OPTS2.Valuetype_arr) is abstract;
   procedure GetObjectParam
     (This : access Typ;
      pszKey : access MSSyst.String.Typ'Class;
      ppunk : access MSSyst.Object.Ref) is abstract;
   procedure GetRunningObjectTable
     (This : access Typ;
      pprot : access Microsoft.VisualStudio.OLE.Interop.IRunningObjectTable.Ref) is abstract;
   procedure RegisterObjectBound
     (This : access Typ;
      punk : access MSSyst.Object.Typ'Class) is abstract;
   procedure RegisterObjectParam
     (This : access Typ;
      pszKey : access MSSyst.String.Typ'Class;
      punk : access MSSyst.Object.Typ'Class) is abstract;
   procedure ReleaseBoundObjects
     (This : access Typ) is abstract;
   procedure RevokeObjectBound
     (This : access Typ;
      punk : access MSSyst.Object.Typ'Class) is abstract;
   procedure RevokeObjectParam
     (This : access Typ;
      pszKey : access MSSyst.String.Typ'Class) is abstract;
   procedure SetBindOptions
     (This : access Typ;
      pbindopts : access Microsoft.VisualStudio.OLE.Interop.BIND_OPTS2.Valuetype_arr) is abstract;
private
   pragma Import (CIL, EnumObjectParam, "EnumObjectParam");
   pragma Import (CIL, GetBindOptions, "GetBindOptions");
   pragma Import (CIL, GetObjectParam, "GetObjectParam");
   pragma Import (CIL, GetRunningObjectTable, "GetRunningObjectTable");
   pragma Import (CIL, RegisterObjectBound, "RegisterObjectBound");
   pragma Import (CIL, RegisterObjectParam, "RegisterObjectParam");
   pragma Import (CIL, ReleaseBoundObjects, "ReleaseBoundObjects");
   pragma Import (CIL, RevokeObjectBound, "RevokeObjectBound");
   pragma Import (CIL, RevokeObjectParam, "RevokeObjectParam");
   pragma Import (CIL, SetBindOptions, "SetBindOptions");
end Microsoft.VisualStudio.OLE.Interop.IBindCtx;
pragma Import (CIL, Microsoft.VisualStudio.OLE.Interop.IBindCtx,
   ".ver 7:1:40304:0 .publickeytoken=( b0 3f 5f 7f 11 d5 0a 3a )",
   "[Microsoft.VisualStudio.OLE.Interop]Microsoft.VisualStudio.OLE.Interop.IBindCtx");
