-- Autogenerated by CIL2Ada v. 2
with MSSyst.Object;
with CIL_Types;
use CIL_Types;
limited with Microsoft.VisualStudio.TextManager.Interop.IVsTextLayer;
package Microsoft.VisualStudio.TextManager.Interop.IVsTextTrackingPoint is
   type Typ is interface;
   type Ref is access all Typ'Class;
   type Ref_addrof is access all Ref;
   type Ref_Arr is array (Natural range <>) of Ref;
   type Ref_Array is access all Ref_Arr;
   type Ref_Array_addrof is access all Ref_Array;
   function GetBehavior
     (This : access Typ;
      pdwBehavior : CIL_Types.Unsigned_Integer_addrof) return Integer is abstract;
   function GetCurrentLineIndex
     (This : access Typ;
      piLine : CIL_Types.Int32_addrof;
      piIndex : CIL_Types.Int32_addrof) return Integer is abstract;
   function GetTextLayer
     (This : access Typ;
      ppLayer : access Microsoft.VisualStudio.TextManager.Interop.IVsTextLayer.Ref) return Integer is abstract;
   function SetBehavior
     (This : access Typ;
      dwBehavior : CIL_Types.Unsigned_Integer) return Integer is abstract;
private
   pragma Import (CIL, GetBehavior, "GetBehavior");
   pragma Import (CIL, GetCurrentLineIndex, "GetCurrentLineIndex");
   pragma Import (CIL, GetTextLayer, "GetTextLayer");
   pragma Import (CIL, SetBehavior, "SetBehavior");
end Microsoft.VisualStudio.TextManager.Interop.IVsTextTrackingPoint;
pragma Import (CIL, Microsoft.VisualStudio.TextManager.Interop.IVsTextTrackingPoint,
   ".ver 7:1:40304:0 .publickeytoken=( b0 3f 5f 7f 11 d5 0a 3a )",
   "[Microsoft.VisualStudio.TextManager.Interop]Microsoft.VisualStudio.TextManager.Interop.IVsTextTrackingPoint");
