-- Autogenerated by CIL2Ada v. 2
with MSSyst.Object;
with CIL_Types;
use CIL_Types;
limited with Microsoft.VisualStudio.OLE.Interop.IOleUndoManager;
with Microsoft.VisualStudio.OLE.Interop.IOleUndoUnit;
with MSSyst.Guid;
limited with MSSyst.String;
package Microsoft.VisualStudio.OLE.Interop.IOleParentUndoUnit is
   type Typ is interface;
   type Ref is access all Typ'Class;
   type Ref_addrof is access all Ref;
   type Ref_Arr is array (Natural range <>) of Ref;
   type Ref_Array is access all Ref_Arr;
   type Ref_Array_addrof is access all Ref_Array;
   procedure Add
     (This : access Typ;
      pUU : access Microsoft.VisualStudio.OLE.Interop.IOleUndoUnit.Typ'Class) is abstract;
   function Close
     (This : access Typ;
      pPUU : access Microsoft.VisualStudio.OLE.Interop.IOleParentUndoUnit.Typ'Class;
      fCommit : Integer) return Integer is abstract;
   procedure Do_k
     (This : access Typ;
      pUndoManager : access Microsoft.VisualStudio.OLE.Interop.IOleUndoManager.Typ'Class) is abstract;
   function FindUnit
     (This : access Typ;
      pUU : access Microsoft.VisualStudio.OLE.Interop.IOleUndoUnit.Typ'Class) return Integer is abstract;
   procedure GetDescription
     (This : access Typ;
      pBstr : access MSSyst.String.Ref) is abstract;
   procedure GetParentState
     (This : access Typ;
      pdwState : CIL_Types.Unsigned_Integer_addrof) is abstract;
   procedure GetUnitType
     (This : access Typ;
      pClsid : access MSSyst.Guid.Valuetype;
      plID : CIL_Types.Int32_addrof) is abstract;
   procedure OnNextAdd
     (This : access Typ) is abstract;
   procedure Open
     (This : access Typ;
      pPUU : access Microsoft.VisualStudio.OLE.Interop.IOleParentUndoUnit.Typ'Class) is abstract;
private
   pragma Import (CIL, Add, "Add");
   pragma Import (CIL, Close, "Close");
   pragma Import (CIL, Do_k, "Do");
   pragma Import (CIL, FindUnit, "FindUnit");
   pragma Import (CIL, GetDescription, "GetDescription");
   pragma Import (CIL, GetParentState, "GetParentState");
   pragma Import (CIL, GetUnitType, "GetUnitType");
   pragma Import (CIL, OnNextAdd, "OnNextAdd");
   pragma Import (CIL, Open, "Open");
end Microsoft.VisualStudio.OLE.Interop.IOleParentUndoUnit;
pragma Import (CIL, Microsoft.VisualStudio.OLE.Interop.IOleParentUndoUnit,
   ".ver 7:1:40304:0 .publickeytoken=( b0 3f 5f 7f 11 d5 0a 3a )",
   "[Microsoft.VisualStudio.OLE.Interop]Microsoft.VisualStudio.OLE.Interop.IOleParentUndoUnit");
