-- Autogenerated by CIL2Ada v. 2
with MSSyst.Object;
with CIL_Types;
use CIL_Types;
limited with Microsoft.VisualStudio.TextManager.Interop.IVsTextView;
limited with Microsoft.VisualStudio.TextManager.Interop.TextViewAction;
package Microsoft.VisualStudio.TextManager.Interop.IVsViewRangeClient is
   type Typ is interface;
   type Ref is access all Typ'Class;
   type Ref_addrof is access all Ref;
   type Ref_Arr is array (Natural range <>) of Ref;
   type Ref_Array is access all Ref_Arr;
   type Ref_Array_addrof is access all Ref_Array;
   function AdjustViewRange
     (This : access Typ;
      pView : access Microsoft.VisualStudio.TextManager.Interop.IVsTextView.Typ'Class;
      action : Microsoft.VisualStudio.TextManager.Interop.TextViewAction.Valuetype;
      iLine : Integer;
      iCount : Integer) return Integer is abstract;
private
   pragma Import (CIL, AdjustViewRange, "AdjustViewRange");
end Microsoft.VisualStudio.TextManager.Interop.IVsViewRangeClient;
pragma Import (CIL, Microsoft.VisualStudio.TextManager.Interop.IVsViewRangeClient,
   ".ver 7:1:40304:0 .publickeytoken=( b0 3f 5f 7f 11 d5 0a 3a )",
   "[Microsoft.VisualStudio.TextManager.Interop]Microsoft.VisualStudio.TextManager.Interop.IVsViewRangeClient");
