-- Autogenerated by CIL2Ada v. 2
with MSSyst.Object;
with CIL_Types;
use CIL_Types;
limited with Microsoft.VisualStudio.OLE.Interop.IConnectionPointContainer;
limited with Microsoft.VisualStudio.OLE.Interop.IEnumConnections;
with MSSyst.Guid;
package Microsoft.VisualStudio.OLE.Interop.IConnectionPoint is
   type Typ is interface;
   type Ref is access all Typ'Class;
   type Ref_addrof is access all Ref;
   type Ref_Arr is array (Natural range <>) of Ref;
   type Ref_Array is access all Ref_Arr;
   type Ref_Array_addrof is access all Ref_Array;
   procedure Advise
     (This : access Typ;
      pUnkSink : access MSSyst.Object.Typ'Class;
      pdwCookie : CIL_Types.Unsigned_Integer_addrof) is abstract;
   procedure EnumConnections
     (This : access Typ;
      ppEnum : access Microsoft.VisualStudio.OLE.Interop.IEnumConnections.Ref) is abstract;
   procedure GetConnectionInterface
     (This : access Typ;
      pIID : access MSSyst.Guid.Valuetype) is abstract;
   procedure GetConnectionPointContainer
     (This : access Typ;
      ppCPC : access Microsoft.VisualStudio.OLE.Interop.IConnectionPointContainer.Ref) is abstract;
   procedure Unadvise
     (This : access Typ;
      dwCookie : CIL_Types.Unsigned_Integer) is abstract;
private
   pragma Import (CIL, Advise, "Advise");
   pragma Import (CIL, EnumConnections, "EnumConnections");
   pragma Import (CIL, GetConnectionInterface, "GetConnectionInterface");
   pragma Import (CIL, GetConnectionPointContainer, "GetConnectionPointContainer");
   pragma Import (CIL, Unadvise, "Unadvise");
end Microsoft.VisualStudio.OLE.Interop.IConnectionPoint;
pragma Import (CIL, Microsoft.VisualStudio.OLE.Interop.IConnectionPoint,
   ".ver 7:1:40304:0 .publickeytoken=( b0 3f 5f 7f 11 d5 0a 3a )",
   "[Microsoft.VisualStudio.OLE.Interop]Microsoft.VisualStudio.OLE.Interop.IConnectionPoint");
