-- Autogenerated by CIL2Ada v. 2
with MSSyst.Object;
with CIL_Types;
use CIL_Types;
limited with MSSyst.IFormatProvider;
limited with MSSyst.String;
limited with MSSyst.TypeCode;
limited with MSSyst.Type_k;
package Microsoft.VisualStudio.TextManager.Interop.TextSelMode is
   type ValueType is (
      SM_STREAM,
      SM_BOX);
   pragma Convention (CIL, ValueType);
   for ValueType use (
      SM_STREAM =>  0,
      SM_BOX =>  1);
   type ValueType_Arr is array (Natural range <>) of ValueType;-- start at 0
   type ValueType_Array is access all ValueType_Arr;
   type ValueType_addrof is access all ValueType;
   type ValueType_array_addrof is access all ValueType_Array;
   function CompareTo
     (This : Valuetype;
      target : access MSSyst.Object.Typ'Class) return Integer;
   function Equals
     (This : Valuetype;
      obj : access MSSyst.Object.Typ'Class) return Standard.Boolean;
   function GetHashCode
     (This : Valuetype) return Integer;
   function GetType
     (This : Valuetype) return access MSSyst.Type_k.Typ'Class;
   function GetTypeCode
     (This : Valuetype) return MSSyst.TypeCode.Valuetype;
   function ToString
     (This : Valuetype;
      provider : access MSSyst.IFormatProvider.Typ'Class) return access MSSyst.String.Typ'Class;
   function ToString
     (This : Valuetype) return access MSSyst.String.Typ'Class;
   function ToString
     (This : Valuetype;
      format : access MSSyst.String.Typ'Class;
      provider : access MSSyst.IFormatProvider.Typ'Class) return access MSSyst.String.Typ'Class;
   function ToString
     (This : Valuetype;
      format : access MSSyst.String.Typ'Class) return access MSSyst.String.Typ'Class;
private
   pragma Import (CIL, CompareTo, "CompareTo");
   pragma Import (CIL, Equals, "Equals");
   pragma Import (CIL, GetHashCode, "GetHashCode");
   pragma Import (CIL, GetType, "GetType");
   pragma Import (CIL, GetTypeCode, "GetTypeCode");
   pragma Import (CIL, ToString, "ToString");
end Microsoft.VisualStudio.TextManager.Interop.TextSelMode;
pragma Import (CIL, Microsoft.VisualStudio.TextManager.Interop.TextSelMode,
   ".ver 7:1:40304:0 .publickeytoken=( b0 3f 5f 7f 11 d5 0a 3a )",
   "[Microsoft.VisualStudio.TextManager.Interop]Microsoft.VisualStudio.TextManager.Interop.TextSelMode");
