-- Autogenerated by CIL2Ada v. 2
with MSSyst.Object;
with CIL_Types;
use CIL_Types;
with Microsoft.VisualStudio.OLE.Interop.FORMATETC;
limited with Microsoft.VisualStudio.OLE.Interop.IAdviseSink;
limited with Microsoft.VisualStudio.OLE.Interop.IEnumFORMATETC;
limited with Microsoft.VisualStudio.OLE.Interop.IEnumSTATDATA;
with Microsoft.VisualStudio.OLE.Interop.STGMEDIUM;
package Microsoft.VisualStudio.OLE.Interop.IDataObject is
   type Typ is interface;
   type Ref is access all Typ'Class;
   type Ref_addrof is access all Ref;
   type Ref_Arr is array (Natural range <>) of Ref;
   type Ref_Array is access all Ref_Arr;
   type Ref_Array_addrof is access all Ref_Array;
   function DAdvise
     (This : access Typ;
      pFormatetc : access Microsoft.VisualStudio.OLE.Interop.FORMATETC.Valuetype_arr;
      ADVF : CIL_Types.Unsigned_Integer;
      pAdvSink : access Microsoft.VisualStudio.OLE.Interop.IAdviseSink.Typ'Class;
      pdwConnection : CIL_Types.Unsigned_Integer_addrof) return Integer is abstract;
   procedure DUnadvise
     (This : access Typ;
      dwConnection : CIL_Types.Unsigned_Integer) is abstract;
   function EnumDAdvise
     (This : access Typ;
      ppenumAdvise : access Microsoft.VisualStudio.OLE.Interop.IEnumSTATDATA.Ref) return Integer is abstract;
   function EnumFormatEtc
     (This : access Typ;
      dwDirection : CIL_Types.Unsigned_Integer;
      ppenumFormatEtc : access Microsoft.VisualStudio.OLE.Interop.IEnumFORMATETC.Ref) return Integer is abstract;
   function GetCanonicalFormatEtc
     (This : access Typ;
      pformatectIn : access Microsoft.VisualStudio.OLE.Interop.FORMATETC.Valuetype_arr;
      pformatetcOut : access Microsoft.VisualStudio.OLE.Interop.FORMATETC.Valuetype_arr) return Integer is abstract;
   procedure GetData
     (This : access Typ;
      pformatetcIn : access Microsoft.VisualStudio.OLE.Interop.FORMATETC.Valuetype_arr;
      pRemoteMedium : access Microsoft.VisualStudio.OLE.Interop.STGMEDIUM.Valuetype_arr) is abstract;
   procedure GetDataHere
     (This : access Typ;
      pFormatetc : access Microsoft.VisualStudio.OLE.Interop.FORMATETC.Valuetype_arr;
      pRemoteMedium : access Microsoft.VisualStudio.OLE.Interop.STGMEDIUM.Valuetype_arr) is abstract;
   function QueryGetData
     (This : access Typ;
      pFormatetc : access Microsoft.VisualStudio.OLE.Interop.FORMATETC.Valuetype_arr) return Integer is abstract;
   procedure SetData
     (This : access Typ;
      pFormatetc : access Microsoft.VisualStudio.OLE.Interop.FORMATETC.Valuetype_arr;
      pmedium : access Microsoft.VisualStudio.OLE.Interop.STGMEDIUM.Valuetype_arr;
      fRelease : Integer) is abstract;
private
   pragma Import (CIL, DAdvise, "DAdvise");
   pragma Import (CIL, DUnadvise, "DUnadvise");
   pragma Import (CIL, EnumDAdvise, "EnumDAdvise");
   pragma Import (CIL, EnumFormatEtc, "EnumFormatEtc");
   pragma Import (CIL, GetCanonicalFormatEtc, "GetCanonicalFormatEtc");
   pragma Import (CIL, GetData, "GetData");
   pragma Import (CIL, GetDataHere, "GetDataHere");
   pragma Import (CIL, QueryGetData, "QueryGetData");
   pragma Import (CIL, SetData, "SetData");
end Microsoft.VisualStudio.OLE.Interop.IDataObject;
pragma Import (CIL, Microsoft.VisualStudio.OLE.Interop.IDataObject,
   ".ver 7:1:40304:0 .publickeytoken=( b0 3f 5f 7f 11 d5 0a 3a )",
   "[Microsoft.VisualStudio.OLE.Interop]Microsoft.VisualStudio.OLE.Interop.IDataObject");
