-- Autogenerated by CIL2Ada v. 2
with MSSyst.Object;
with CIL_Types;
use CIL_Types;
limited with Microsoft.VisualStudio.OLE.Interop.IOleUndoManager;
limited with Microsoft.VisualStudio.TextManager.Interop.IVsEnumLineMarkers;
with Microsoft.VisualStudio.TextManager.Interop.IVsTextBuffer;
limited with Microsoft.VisualStudio.TextManager.Interop.IVsTextLineMarker;
limited with Microsoft.VisualStudio.TextManager.Interop.IVsTextLinesEvents;
limited with Microsoft.VisualStudio.TextManager.Interop.IVsTextMarkerClient;
with Microsoft.VisualStudio.TextManager.Interop.LINEDATA;
with Microsoft.VisualStudio.TextManager.Interop.LINEDATAEX;
with Microsoft.VisualStudio.TextManager.Interop.MARKERDATA;
with Microsoft.VisualStudio.TextManager.Interop.TextSpan;
with MSSyst.Guid;
limited with MSSyst.String;
package Microsoft.VisualStudio.TextManager.Interop.IVsTextLines is
   type Typ is interface;
   type Ref is access all Typ'Class;
   type Ref_addrof is access all Ref;
   type Ref_Arr is array (Natural range <>) of Ref;
   type Ref_Array is access all Ref_Arr;
   type Ref_Array_addrof is access all Ref_Array;
   function AdviseTextLinesEvents
     (This : access Typ;
      pSink : access Microsoft.VisualStudio.TextManager.Interop.IVsTextLinesEvents.Typ'Class;
      pdwCookie : CIL_Types.Unsigned_Integer_addrof) return Integer is abstract;
   function CanReplaceLines
     (This : access Typ;
      iStartLine : Integer;
      iStartIndex : Integer;
      iEndLine : Integer;
      iEndIndex : Integer;
      iNewLen : Integer) return Integer is abstract;
   function CopyLineText
     (This : access Typ;
      iStartLine : Integer;
      iStartIndex : Integer;
      iEndLine : Integer;
      iEndIndex : Integer;
      pszBuf : CIL_Types.native_int;
      pcchBuf : CIL_Types.Int32_addrof) return Integer is abstract;
   function CreateEditPoint
     (This : access Typ;
      iLine : Integer;
      iIndex : Integer;
      ppEditPoint : access MSSyst.Object.Ref) return Integer is abstract;
   function CreateLineMarker
     (This : access Typ;
      iMarkerType : Integer;
      iStartLine : Integer;
      iStartIndex : Integer;
      iEndLine : Integer;
      iEndIndex : Integer;
      pClient : access Microsoft.VisualStudio.TextManager.Interop.IVsTextMarkerClient.Typ'Class;
      ppMarker : access Microsoft.VisualStudio.TextManager.Interop.IVsTextLineMarker.Ref_arr) return Integer is abstract;
   function CreateTextPoint
     (This : access Typ;
      iLine : Integer;
      iIndex : Integer;
      ppTextPoint : access MSSyst.Object.Ref) return Integer is abstract;
   function EnumMarkers
     (This : access Typ;
      iStartLine : Integer;
      iStartIndex : Integer;
      iEndLine : Integer;
      iEndIndex : Integer;
      iMarkerType : Integer;
      dwFlags : CIL_Types.Unsigned_Integer;
      ppEnum : access Microsoft.VisualStudio.TextManager.Interop.IVsEnumLineMarkers.Ref) return Integer is abstract;
   function FindMarkerByLineIndex
     (This : access Typ;
      iMarkerType : Integer;
      iStartingLine : Integer;
      iStartingIndex : Integer;
      dwFlags : CIL_Types.Unsigned_Integer;
      ppMarker : access Microsoft.VisualStudio.TextManager.Interop.IVsTextLineMarker.Ref) return Integer is abstract;
   function GetLanguageServiceID
     (This : access Typ;
      pguidLangService : access MSSyst.Guid.Valuetype) return Integer is abstract;
   function GetLastLineIndex
     (This : access Typ;
      piLine : CIL_Types.Int32_addrof;
      piIndex : CIL_Types.Int32_addrof) return Integer is abstract;
   function GetLengthOfLine
     (This : access Typ;
      iLine : Integer;
      piLength : CIL_Types.Int32_addrof) return Integer is abstract;
   function GetLineCount
     (This : access Typ;
      piLineCount : CIL_Types.Int32_addrof) return Integer is abstract;
   function GetLineData
     (This : access Typ;
      iLine : Integer;
      pLineData : access Microsoft.VisualStudio.TextManager.Interop.LINEDATA.Valuetype_arr;
      pMarkerData : access Microsoft.VisualStudio.TextManager.Interop.MARKERDATA.Valuetype_arr) return Integer is abstract;
   function GetLineDataEx
     (This : access Typ;
      dwFlags : CIL_Types.Unsigned_Integer;
      iLine : Integer;
      iStartIndex : Integer;
      iEndIndex : Integer;
      pLineData : access Microsoft.VisualStudio.TextManager.Interop.LINEDATAEX.Valuetype_arr;
      pMarkerData : access Microsoft.VisualStudio.TextManager.Interop.MARKERDATA.Valuetype_arr) return Integer is abstract;
   function GetLineIndexOfPosition
     (This : access Typ;
      iPosition : Integer;
      piLine : CIL_Types.Int32_addrof;
      piColumn : CIL_Types.Int32_addrof) return Integer is abstract;
   function GetLineText
     (This : access Typ;
      iStartLine : Integer;
      iStartIndex : Integer;
      iEndLine : Integer;
      iEndIndex : Integer;
      pbstrBuf : access MSSyst.String.Ref) return Integer is abstract;
   function GetMarkerData
     (This : access Typ;
      iTopLine : Integer;
      iBottomLine : Integer;
      pMarkerData : access Microsoft.VisualStudio.TextManager.Interop.MARKERDATA.Valuetype_arr) return Integer is abstract;
   function GetPairExtents
     (This : access Typ;
      pSpanIn : access Microsoft.VisualStudio.TextManager.Interop.TextSpan.Valuetype_arr;
      pSpanOut : access Microsoft.VisualStudio.TextManager.Interop.TextSpan.Valuetype_arr) return Integer is abstract;
   function GetPositionOfLine
     (This : access Typ;
      iLine : Integer;
      piPosition : CIL_Types.Int32_addrof) return Integer is abstract;
   function GetPositionOfLineIndex
     (This : access Typ;
      iLine : Integer;
      iIndex : Integer;
      piPosition : CIL_Types.Int32_addrof) return Integer is abstract;
   function GetSize
     (This : access Typ;
      piLength : CIL_Types.Int32_addrof) return Integer is abstract;
   function GetStateFlags
     (This : access Typ;
      pdwReadOnlyFlags : CIL_Types.Unsigned_Integer_addrof) return Integer is abstract;
   function GetUndoManager
     (This : access Typ;
      ppUndoManager : access Microsoft.VisualStudio.OLE.Interop.IOleUndoManager.Ref) return Integer is abstract;
   function InitializeContent
     (This : access Typ;
      pszText : access MSSyst.String.Typ'Class;
      iLength : Integer) return Integer is abstract;
   function IVsTextLinesReserved1
     (This : access Typ;
      iLine : Integer;
      pLineData : access Microsoft.VisualStudio.TextManager.Interop.LINEDATA.Valuetype_arr;
      fAttributes : Integer) return Integer is abstract;
   function LockBuffer
     (This : access Typ) return Integer is abstract;
   function LockBufferEx
     (This : access Typ;
      dwFlags : CIL_Types.Unsigned_Integer) return Integer is abstract;
   function ReleaseLineData
     (This : access Typ;
      pLineData : access Microsoft.VisualStudio.TextManager.Interop.LINEDATA.Valuetype_arr) return Integer is abstract;
   function ReleaseLineDataEx
     (This : access Typ;
      pLineData : access Microsoft.VisualStudio.TextManager.Interop.LINEDATAEX.Valuetype_arr) return Integer is abstract;
   function ReleaseMarkerData
     (This : access Typ;
      pMarkerData : access Microsoft.VisualStudio.TextManager.Interop.MARKERDATA.Valuetype_arr) return Integer is abstract;
   function Reload
     (This : access Typ;
      fUndoable : Integer) return Integer is abstract;
   function ReloadLines
     (This : access Typ;
      iStartLine : Integer;
      iStartIndex : Integer;
      iEndLine : Integer;
      iEndIndex : Integer;
      pszText : CIL_Types.native_int;
      iNewLen : Integer;
      pChangedSpan : access Microsoft.VisualStudio.TextManager.Interop.TextSpan.Valuetype_arr) return Integer is abstract;
   function ReplaceLines
     (This : access Typ;
      iStartLine : Integer;
      iStartIndex : Integer;
      iEndLine : Integer;
      iEndIndex : Integer;
      pszText : CIL_Types.native_int;
      iNewLen : Integer;
      pChangedSpan : access Microsoft.VisualStudio.TextManager.Interop.TextSpan.Valuetype_arr) return Integer is abstract;
   function ReplaceLinesEx
     (This : access Typ;
      dwFlags : CIL_Types.Unsigned_Integer;
      iStartLine : Integer;
      iStartIndex : Integer;
      iEndLine : Integer;
      iEndIndex : Integer;
      pszText : CIL_Types.native_int;
      iNewLen : Integer;
      pChangedSpan : access Microsoft.VisualStudio.TextManager.Interop.TextSpan.Valuetype_arr) return Integer is abstract;
   function Reserved1
     (This : access Typ) return Integer is abstract;
   function Reserved10
     (This : access Typ) return Integer is abstract;
   function Reserved2
     (This : access Typ) return Integer is abstract;
   function Reserved3
     (This : access Typ) return Integer is abstract;
   function Reserved4
     (This : access Typ) return Integer is abstract;
   function Reserved5
     (This : access Typ) return Integer is abstract;
   function Reserved6
     (This : access Typ) return Integer is abstract;
   function Reserved7
     (This : access Typ) return Integer is abstract;
   function Reserved8
     (This : access Typ) return Integer is abstract;
   function Reserved9
     (This : access Typ) return Integer is abstract;
   function SetLanguageServiceID
     (This : access Typ;
      guidLangService : access MSSyst.Guid.Valuetype) return Integer is abstract;
   function SetStateFlags
     (This : access Typ;
      dwReadOnlyFlags : CIL_Types.Unsigned_Integer) return Integer is abstract;
   function UnadviseTextLinesEvents
     (This : access Typ;
      dwCookie : CIL_Types.Unsigned_Integer) return Integer is abstract;
   function UnlockBuffer
     (This : access Typ) return Integer is abstract;
   function UnlockBufferEx
     (This : access Typ;
      dwFlags : CIL_Types.Unsigned_Integer) return Integer is abstract;
private
   pragma Import (CIL, AdviseTextLinesEvents, "AdviseTextLinesEvents");
   pragma Import (CIL, CanReplaceLines, "CanReplaceLines");
   pragma Import (CIL, CopyLineText, "CopyLineText");
   pragma Import (CIL, CreateEditPoint, "CreateEditPoint");
   pragma Import (CIL, CreateLineMarker, "CreateLineMarker");
   pragma Import (CIL, CreateTextPoint, "CreateTextPoint");
   pragma Import (CIL, EnumMarkers, "EnumMarkers");
   pragma Import (CIL, FindMarkerByLineIndex, "FindMarkerByLineIndex");
   pragma Import (CIL, GetLanguageServiceID, "GetLanguageServiceID");
   pragma Import (CIL, GetLastLineIndex, "GetLastLineIndex");
   pragma Import (CIL, GetLengthOfLine, "GetLengthOfLine");
   pragma Import (CIL, GetLineCount, "GetLineCount");
   pragma Import (CIL, GetLineData, "GetLineData");
   pragma Import (CIL, GetLineDataEx, "GetLineDataEx");
   pragma Import (CIL, GetLineIndexOfPosition, "GetLineIndexOfPosition");
   pragma Import (CIL, GetLineText, "GetLineText");
   pragma Import (CIL, GetMarkerData, "GetMarkerData");
   pragma Import (CIL, GetPairExtents, "GetPairExtents");
   pragma Import (CIL, GetPositionOfLine, "GetPositionOfLine");
   pragma Import (CIL, GetPositionOfLineIndex, "GetPositionOfLineIndex");
   pragma Import (CIL, GetSize, "GetSize");
   pragma Import (CIL, GetStateFlags, "GetStateFlags");
   pragma Import (CIL, GetUndoManager, "GetUndoManager");
   pragma Import (CIL, InitializeContent, "InitializeContent");
   pragma Import (CIL, IVsTextLinesReserved1, "IVsTextLinesReserved1");
   pragma Import (CIL, LockBuffer, "LockBuffer");
   pragma Import (CIL, LockBufferEx, "LockBufferEx");
   pragma Import (CIL, ReleaseLineData, "ReleaseLineData");
   pragma Import (CIL, ReleaseLineDataEx, "ReleaseLineDataEx");
   pragma Import (CIL, ReleaseMarkerData, "ReleaseMarkerData");
   pragma Import (CIL, Reload, "Reload");
   pragma Import (CIL, ReloadLines, "ReloadLines");
   pragma Import (CIL, ReplaceLines, "ReplaceLines");
   pragma Import (CIL, ReplaceLinesEx, "ReplaceLinesEx");
   pragma Import (CIL, Reserved1, "Reserved1");
   pragma Import (CIL, Reserved10, "Reserved10");
   pragma Import (CIL, Reserved2, "Reserved2");
   pragma Import (CIL, Reserved3, "Reserved3");
   pragma Import (CIL, Reserved4, "Reserved4");
   pragma Import (CIL, Reserved5, "Reserved5");
   pragma Import (CIL, Reserved6, "Reserved6");
   pragma Import (CIL, Reserved7, "Reserved7");
   pragma Import (CIL, Reserved8, "Reserved8");
   pragma Import (CIL, Reserved9, "Reserved9");
   pragma Import (CIL, SetLanguageServiceID, "SetLanguageServiceID");
   pragma Import (CIL, SetStateFlags, "SetStateFlags");
   pragma Import (CIL, UnadviseTextLinesEvents, "UnadviseTextLinesEvents");
   pragma Import (CIL, UnlockBuffer, "UnlockBuffer");
   pragma Import (CIL, UnlockBufferEx, "UnlockBufferEx");
end Microsoft.VisualStudio.TextManager.Interop.IVsTextLines;
pragma Import (CIL, Microsoft.VisualStudio.TextManager.Interop.IVsTextLines,
   ".ver 7:1:40304:0 .publickeytoken=( b0 3f 5f 7f 11 d5 0a 3a )",
   "[Microsoft.VisualStudio.TextManager.Interop]Microsoft.VisualStudio.TextManager.Interop.IVsTextLines");
