-- Autogenerated by CIL2Ada v. 2
with MSSyst.Object;
with CIL_Types;
use CIL_Types;
with Microsoft.VisualStudio.TextManager.Interop.TextSpan;
package Microsoft.VisualStudio.TextManager.Interop.IVsEnumTextSpans is
   type Typ is interface;
   type Ref is access all Typ'Class;
   type Ref_addrof is access all Ref;
   type Ref_Arr is array (Natural range <>) of Ref;
   type Ref_Array is access all Ref_Arr;
   type Ref_Array_addrof is access all Ref_Array;
   function GetCount
     (This : access Typ;
      pcSpans : CIL_Types.Unsigned_Integer_addrof) return Integer is abstract;
   function Next
     (This : access Typ;
      cEl : CIL_Types.Unsigned_Integer;
      ppOut : access Microsoft.VisualStudio.TextManager.Interop.TextSpan.Valuetype_arr;
      pcElFetched : CIL_Types.Unsigned_Integer_addrof) return Integer is abstract;
   function Reset
     (This : access Typ) return Integer is abstract;
private
   pragma Import (CIL, GetCount, "GetCount");
   pragma Import (CIL, Next, "Next");
   pragma Import (CIL, Reset, "Reset");
end Microsoft.VisualStudio.TextManager.Interop.IVsEnumTextSpans;
pragma Import (CIL, Microsoft.VisualStudio.TextManager.Interop.IVsEnumTextSpans,
   ".ver 7:1:40304:0 .publickeytoken=( b0 3f 5f 7f 11 d5 0a 3a )",
   "[Microsoft.VisualStudio.TextManager.Interop]Microsoft.VisualStudio.TextManager.Interop.IVsEnumTextSpans");
