-- Autogenerated by CIL2Ada v. 2
with MSSyst.Object;
with CIL_Types;
use CIL_Types;
limited with Microsoft.VisualStudio.OLE.Interop.IOleUndoManager;
with MSSyst.Guid;
limited with MSSyst.String;
package Microsoft.VisualStudio.OLE.Interop.IOleUndoUnit is
   type Typ is interface;
   type Ref is access all Typ'Class;
   type Ref_addrof is access all Ref;
   type Ref_Arr is array (Natural range <>) of Ref;
   type Ref_Array is access all Ref_Arr;
   type Ref_Array_addrof is access all Ref_Array;
   procedure Do_k
     (This : access Typ;
      pUndoManager : access Microsoft.VisualStudio.OLE.Interop.IOleUndoManager.Typ'Class) is abstract;
   procedure GetDescription
     (This : access Typ;
      pBstr : access MSSyst.String.Ref) is abstract;
   procedure GetUnitType
     (This : access Typ;
      pClsid : access MSSyst.Guid.Valuetype;
      plID : CIL_Types.Int32_addrof) is abstract;
   procedure OnNextAdd
     (This : access Typ) is abstract;
private
   pragma Import (CIL, Do_k, "Do");
   pragma Import (CIL, GetDescription, "GetDescription");
   pragma Import (CIL, GetUnitType, "GetUnitType");
   pragma Import (CIL, OnNextAdd, "OnNextAdd");
end Microsoft.VisualStudio.OLE.Interop.IOleUndoUnit;
pragma Import (CIL, Microsoft.VisualStudio.OLE.Interop.IOleUndoUnit,
   ".ver 7:1:40304:0 .publickeytoken=( b0 3f 5f 7f 11 d5 0a 3a )",
   "[Microsoft.VisualStudio.OLE.Interop]Microsoft.VisualStudio.OLE.Interop.IOleUndoUnit");
