-- Autogenerated by CIL2Ada v. 2
with MSSyst.Object;
with CIL_Types;
use CIL_Types;
with MSSyst.Guid;
package Microsoft.VisualStudio.OLE.Interop.IPersist is
   type Typ is interface;
   type Ref is access all Typ'Class;
   type Ref_addrof is access all Ref;
   type Ref_Arr is array (Natural range <>) of Ref;
   type Ref_Array is access all Ref_Arr;
   type Ref_Array_addrof is access all Ref_Array;
   function GetClassID
     (This : access Typ;
      pClassID : access MSSyst.Guid.Valuetype) return Integer is abstract;
private
   pragma Import (CIL, GetClassID, "GetClassID");
end Microsoft.VisualStudio.OLE.Interop.IPersist;
pragma Import (CIL, Microsoft.VisualStudio.OLE.Interop.IPersist,
   ".ver 7:1:40304:0 .publickeytoken=( b0 3f 5f 7f 11 d5 0a 3a )",
   "[Microsoft.VisualStudio.OLE.Interop]Microsoft.VisualStudio.OLE.Interop.IPersist");
