-- Autogenerated by CIL2Ada v. 2
with MSSyst.Object;
with CIL_Types;
use CIL_Types;
limited with Microsoft.VisualStudio.TextManager.Interop.IVsTextMarker;
limited with MSSyst.String;
package Microsoft.VisualStudio.TextManager.Interop.IVsTextMarkerClient is
   type Typ is interface;
   type Ref is access all Typ'Class;
   type Ref_addrof is access all Ref;
   type Ref_Arr is array (Natural range <>) of Ref;
   type Ref_Array is access all Ref_Arr;
   type Ref_Array_addrof is access all Ref_Array;
   function ExecMarkerCommand
     (This : access Typ;
      pMarker : access Microsoft.VisualStudio.TextManager.Interop.IVsTextMarker.Typ'Class;
      iItem : Integer) return Integer is abstract;
   function GetMarkerCommandInfo
     (This : access Typ;
      pMarker : access Microsoft.VisualStudio.TextManager.Interop.IVsTextMarker.Typ'Class;
      iItem : Integer;
      pbstrText : access MSSyst.String.Ref_arr;
      pcmdf : CIL_Types.Unsigned_Integer_Arr) return Integer is abstract;
   function GetTipText
     (This : access Typ;
      pMarker : access Microsoft.VisualStudio.TextManager.Interop.IVsTextMarker.Typ'Class;
      pbstrText : access MSSyst.String.Ref_arr) return Integer is abstract;
   procedure MarkerInvalidated
     (This : access Typ) is abstract;
   function OnAfterMarkerChange
     (This : access Typ;
      pMarker : access Microsoft.VisualStudio.TextManager.Interop.IVsTextMarker.Typ'Class) return Integer is abstract;
   procedure OnAfterSpanReload
     (This : access Typ) is abstract;
   procedure OnBeforeBufferClose
     (This : access Typ) is abstract;
   procedure OnBufferSave
     (This : access Typ;
      pszFileName : access MSSyst.String.Typ'Class) is abstract;
private
   pragma Import (CIL, ExecMarkerCommand, "ExecMarkerCommand");
   pragma Import (CIL, GetMarkerCommandInfo, "GetMarkerCommandInfo");
   pragma Import (CIL, GetTipText, "GetTipText");
   pragma Import (CIL, MarkerInvalidated, "MarkerInvalidated");
   pragma Import (CIL, OnAfterMarkerChange, "OnAfterMarkerChange");
   pragma Import (CIL, OnAfterSpanReload, "OnAfterSpanReload");
   pragma Import (CIL, OnBeforeBufferClose, "OnBeforeBufferClose");
   pragma Import (CIL, OnBufferSave, "OnBufferSave");
end Microsoft.VisualStudio.TextManager.Interop.IVsTextMarkerClient;
pragma Import (CIL, Microsoft.VisualStudio.TextManager.Interop.IVsTextMarkerClient,
   ".ver 7:1:40304:0 .publickeytoken=( b0 3f 5f 7f 11 d5 0a 3a )",
   "[Microsoft.VisualStudio.TextManager.Interop]Microsoft.VisualStudio.TextManager.Interop.IVsTextMarkerClient");
