-- Autogenerated by CIL2Ada v. 2
with MSSyst.Object;
with CIL_Types;
use CIL_Types;
with Microsoft.VisualStudio.OLE.Interop.RECT;
limited with Microsoft.VisualStudio.TextManager.Interop.IVsTextLayer;
with Microsoft.VisualStudio.TextManager.Interop.IVsTextMarker;
with Microsoft.VisualStudio.TextManager.Interop.TextSpan;
with MSSyst.Guid;
limited with MSSyst.String;
package Microsoft.VisualStudio.TextManager.Interop.IVsTextLayerMarker is
   type Typ is interface;
   type Ref is access all Typ'Class;
   type Ref_addrof is access all Ref;
   type Ref_Arr is array (Natural range <>) of Ref;
   type Ref_Array is access all Ref_Arr;
   type Ref_Array_addrof is access all Ref_Array;
   function DrawGlyph
     (This : access Typ;
      hdc : CIL_Types.native_int;
      pRect : access Microsoft.VisualStudio.OLE.Interop.RECT.Valuetype_arr) return Integer is abstract;
   function DrawGlyphEx
     (This : access Typ;
      dwFlags : CIL_Types.Unsigned_Integer;
      hdc : CIL_Types.native_int;
      pRect : access Microsoft.VisualStudio.OLE.Interop.RECT.Valuetype_arr;
      iLineHeight : Integer) return Integer is abstract;
   function ExecMarkerCommand
     (This : access Typ;
      iItem : Integer) return Integer is abstract;
   function GetBehavior
     (This : access Typ;
      pdwBehavior : CIL_Types.Unsigned_Integer_addrof) return Integer is abstract;
   function GetCurrentSpan
     (This : access Typ;
      pSpan : access Microsoft.VisualStudio.TextManager.Interop.TextSpan.Valuetype_arr) return Integer is abstract;
   function GetMarkerCommandInfo
     (This : access Typ;
      iItem : Integer;
      pbstrText : access MSSyst.String.Ref_arr;
      pcmdf : CIL_Types.Unsigned_Integer_Arr) return Integer is abstract;
   function GetPriorityIndex
     (This : access Typ;
      piPriorityIndex : CIL_Types.Int32_addrof) return Integer is abstract;
   function GetTextLayer
     (This : access Typ;
      ppLayer : access Microsoft.VisualStudio.TextManager.Interop.IVsTextLayer.Ref) return Integer is abstract;
   function GetTipText
     (This : access Typ;
      pbstrText : access MSSyst.String.Ref_arr) return Integer is abstract;
   function GetType
     (This : access Typ;
      piMarkerType : CIL_Types.Int32_addrof) return Integer is abstract;
   function GetVisualStyle
     (This : access Typ;
      pdwFlags : CIL_Types.Unsigned_Integer_addrof) return Integer is abstract;
   function Invalidate
     (This : access Typ) return Integer is abstract;
   function IsInvalidated
     (This : access Typ) return Integer is abstract;
   function QueryClientInterface
     (This : access Typ;
      iid : access MSSyst.Guid.Valuetype;
      ppClient : CIL_Types.native_int_addrof) return Integer is abstract;
   function ResetSpan
     (This : access Typ;
      iStartLine : Integer;
      iStartIndex : Integer;
      iEndLine : Integer;
      iEndIndex : Integer) return Integer is abstract;
   function SetBehavior
     (This : access Typ;
      dwBehavior : CIL_Types.Unsigned_Integer) return Integer is abstract;
   function SetType
     (This : access Typ;
      iMarkerType : Integer) return Integer is abstract;
   function SetVisualStyle
     (This : access Typ;
      dwFlags : CIL_Types.Unsigned_Integer) return Integer is abstract;
   function UnadviseClient
     (This : access Typ) return Integer is abstract;
private
   pragma Import (CIL, DrawGlyph, "DrawGlyph");
   pragma Import (CIL, DrawGlyphEx, "DrawGlyphEx");
   pragma Import (CIL, ExecMarkerCommand, "ExecMarkerCommand");
   pragma Import (CIL, GetBehavior, "GetBehavior");
   pragma Import (CIL, GetCurrentSpan, "GetCurrentSpan");
   pragma Import (CIL, GetMarkerCommandInfo, "GetMarkerCommandInfo");
   pragma Import (CIL, GetPriorityIndex, "GetPriorityIndex");
   pragma Import (CIL, GetTextLayer, "GetTextLayer");
   pragma Import (CIL, GetTipText, "GetTipText");
   pragma Import (CIL, GetType, "GetType");
   pragma Import (CIL, GetVisualStyle, "GetVisualStyle");
   pragma Import (CIL, Invalidate, "Invalidate");
   pragma Import (CIL, IsInvalidated, "IsInvalidated");
   pragma Import (CIL, QueryClientInterface, "QueryClientInterface");
   pragma Import (CIL, ResetSpan, "ResetSpan");
   pragma Import (CIL, SetBehavior, "SetBehavior");
   pragma Import (CIL, SetType, "SetType");
   pragma Import (CIL, SetVisualStyle, "SetVisualStyle");
   pragma Import (CIL, UnadviseClient, "UnadviseClient");
end Microsoft.VisualStudio.TextManager.Interop.IVsTextLayerMarker;
pragma Import (CIL, Microsoft.VisualStudio.TextManager.Interop.IVsTextLayerMarker,
   ".ver 7:1:40304:0 .publickeytoken=( b0 3f 5f 7f 11 d5 0a 3a )",
   "[Microsoft.VisualStudio.TextManager.Interop]Microsoft.VisualStudio.TextManager.Interop.IVsTextLayerMarker");
