-- Autogenerated by CIL2Ada v. 2
with MSSyst.Object;
with CIL_Types;
use CIL_Types;
with Microsoft.VisualStudio.OLE.Interop.FILETIME;
limited with Microsoft.VisualStudio.OLE.Interop.IEnumMoniker;
limited with Microsoft.VisualStudio.OLE.Interop.IMoniker;
package Microsoft.VisualStudio.OLE.Interop.IRunningObjectTable is
   type Typ is interface;
   type Ref is access all Typ'Class;
   type Ref_addrof is access all Ref;
   type Ref_Arr is array (Natural range <>) of Ref;
   type Ref_Array is access all Ref_Arr;
   type Ref_Array_addrof is access all Ref_Array;
   procedure EnumRunning
     (This : access Typ;
      ppenumMoniker : access Microsoft.VisualStudio.OLE.Interop.IEnumMoniker.Ref) is abstract;
   procedure GetObject
     (This : access Typ;
      pmkObjectName : access Microsoft.VisualStudio.OLE.Interop.IMoniker.Typ'Class;
      ppunkObject : access MSSyst.Object.Ref) is abstract;
   procedure GetTimeOfLastChange
     (This : access Typ;
      pmkObjectName : access Microsoft.VisualStudio.OLE.Interop.IMoniker.Typ'Class;
      pFileTime : access Microsoft.VisualStudio.OLE.Interop.FILETIME.Valuetype_arr) is abstract;
   function IsRunning
     (This : access Typ;
      pmkObjectName : access Microsoft.VisualStudio.OLE.Interop.IMoniker.Typ'Class) return Integer is abstract;
   procedure NoteChangeTime
     (This : access Typ;
      dwRegister : CIL_Types.Unsigned_Integer;
      pFileTime : access Microsoft.VisualStudio.OLE.Interop.FILETIME.Valuetype_arr) is abstract;
   procedure Register
     (This : access Typ;
      grfFlags : CIL_Types.Unsigned_Integer;
      punkObject : access MSSyst.Object.Typ'Class;
      pmkObjectName : access Microsoft.VisualStudio.OLE.Interop.IMoniker.Typ'Class;
      pdwRegister : CIL_Types.Unsigned_Integer_addrof) is abstract;
   procedure Revoke
     (This : access Typ;
      dwRegister : CIL_Types.Unsigned_Integer) is abstract;
private
   pragma Import (CIL, EnumRunning, "EnumRunning");
   pragma Import (CIL, GetObject, "GetObject");
   pragma Import (CIL, GetTimeOfLastChange, "GetTimeOfLastChange");
   pragma Import (CIL, IsRunning, "IsRunning");
   pragma Import (CIL, NoteChangeTime, "NoteChangeTime");
   pragma Import (CIL, Register, "Register");
   pragma Import (CIL, Revoke, "Revoke");
end Microsoft.VisualStudio.OLE.Interop.IRunningObjectTable;
pragma Import (CIL, Microsoft.VisualStudio.OLE.Interop.IRunningObjectTable,
   ".ver 7:1:40304:0 .publickeytoken=( b0 3f 5f 7f 11 d5 0a 3a )",
   "[Microsoft.VisualStudio.OLE.Interop]Microsoft.VisualStudio.OLE.Interop.IRunningObjectTable");
