-- Autogenerated by CIL2Ada v. 2
with MSSyst.Object;
with CIL_Types;
use CIL_Types;
with Microsoft.VisualStudio.OLE.Interop.OLECMD;
with MSSyst.Guid;
package Microsoft.VisualStudio.OLE.Interop.IOleCommandTarget is
   type Typ is interface;
   type Ref is access all Typ'Class;
   type Ref_addrof is access all Ref;
   type Ref_Arr is array (Natural range <>) of Ref;
   type Ref_Array is access all Ref_Arr;
   type Ref_Array_addrof is access all Ref_Array;
   function Exec
     (This : access Typ;
      pguidCmdGroup : access MSSyst.Guid.Valuetype;
      nCmdID : CIL_Types.Unsigned_Integer;
      nCmdexecopt : CIL_Types.Unsigned_Integer;
      pvaIn : CIL_Types.native_int;
      pvaOut : CIL_Types.native_int) return Integer is abstract;
   function QueryStatus
     (This : access Typ;
      pguidCmdGroup : access MSSyst.Guid.Valuetype;
      cCmds : CIL_Types.Unsigned_Integer;
      prgCmds : access Microsoft.VisualStudio.OLE.Interop.OLECMD.Valuetype_arr;
      pCmdText : CIL_Types.native_int) return Integer is abstract;
private
   pragma Import (CIL, Exec, "Exec");
   pragma Import (CIL, QueryStatus, "QueryStatus");
end Microsoft.VisualStudio.OLE.Interop.IOleCommandTarget;
pragma Import (CIL, Microsoft.VisualStudio.OLE.Interop.IOleCommandTarget,
   ".ver 7:1:40304:0 .publickeytoken=( b0 3f 5f 7f 11 d5 0a 3a )",
   "[Microsoft.VisualStudio.OLE.Interop]Microsoft.VisualStudio.OLE.Interop.IOleCommandTarget");
