-- Autogenerated by CIL2Ada v. 2
with MSSyst.Object;
with CIL_Types;
use CIL_Types;
limited with MSSyst.String;
package Microsoft.VisualStudio.TextManager.Interop.IVsCompletionSet is
   type Typ is interface;
   type Ref is access all Typ'Class;
   type Ref_addrof is access all Ref;
   type Ref_Arr is array (Natural range <>) of Ref;
   type Ref_Array is access all Ref_Arr;
   type Ref_Array_addrof is access all Ref_Array;
   procedure Dismiss
     (This : access Typ) is abstract;
   function GetBestMatch
     (This : access Typ;
      pszSoFar : access MSSyst.String.Typ'Class;
      iLength : Integer;
      piIndex : CIL_Types.Int32_addrof;
      pdwFlags : CIL_Types.Unsigned_Integer_addrof) return Integer is abstract;
   function GetCount
     (This : access Typ) return Integer is abstract;
   function GetDescriptionText
     (This : access Typ;
      iIndex : Integer;
      pbstrDescription : access MSSyst.String.Ref) return Integer is abstract;
   function GetDisplayText
     (This : access Typ;
      iIndex : Integer;
      ppszText : access MSSyst.String.Ref;
      piGlyph : CIL_Types.Int32_Arr) return Integer is abstract;
   function GetFlags
     (This : access Typ) return CIL_Types.Unsigned_Integer is abstract;
   function GetImageList
     (This : access Typ;
      phImages : CIL_Types.native_int_addrof) return Integer is abstract;
   function GetInitialExtent
     (This : access Typ;
      piLine : CIL_Types.Int32_addrof;
      piStartCol : CIL_Types.Int32_addrof;
      piEndCol : CIL_Types.Int32_addrof) return Integer is abstract;
   function OnCommit
     (This : access Typ;
      pszSoFar : access MSSyst.String.Typ'Class;
      iIndex : Integer;
      fSelected : Integer;
      cCommit : CIL_Types.unsigned_int16;
      pbstrCompleteWord : access MSSyst.String.Ref) return Integer is abstract;
private
   pragma Import (CIL, Dismiss, "Dismiss");
   pragma Import (CIL, GetBestMatch, "GetBestMatch");
   pragma Import (CIL, GetCount, "GetCount");
   pragma Import (CIL, GetDescriptionText, "GetDescriptionText");
   pragma Import (CIL, GetDisplayText, "GetDisplayText");
   pragma Import (CIL, GetFlags, "GetFlags");
   pragma Import (CIL, GetImageList, "GetImageList");
   pragma Import (CIL, GetInitialExtent, "GetInitialExtent");
   pragma Import (CIL, OnCommit, "OnCommit");
end Microsoft.VisualStudio.TextManager.Interop.IVsCompletionSet;
pragma Import (CIL, Microsoft.VisualStudio.TextManager.Interop.IVsCompletionSet,
   ".ver 7:1:40304:0 .publickeytoken=( b0 3f 5f 7f 11 d5 0a 3a )",
   "[Microsoft.VisualStudio.TextManager.Interop]Microsoft.VisualStudio.TextManager.Interop.IVsCompletionSet");
