-- Autogenerated by CIL2Ada v. 2
with MSSyst.Object;
with CIL_Types;
use CIL_Types;
limited with Microsoft.VisualStudio.OLE.Interop.IEnumOleUndoUnits;
limited with Microsoft.VisualStudio.OLE.Interop.IOleParentUndoUnit;
limited with Microsoft.VisualStudio.OLE.Interop.IOleUndoUnit;
limited with MSSyst.String;
package Microsoft.VisualStudio.OLE.Interop.IOleUndoManager is
   type Typ is interface;
   type Ref is access all Typ'Class;
   type Ref_addrof is access all Ref;
   type Ref_Arr is array (Natural range <>) of Ref;
   type Ref_Array is access all Ref_Arr;
   type Ref_Array_addrof is access all Ref_Array;
   procedure Add
     (This : access Typ;
      pUU : access Microsoft.VisualStudio.OLE.Interop.IOleUndoUnit.Typ'Class) is abstract;
   function Close
     (This : access Typ;
      pPUU : access Microsoft.VisualStudio.OLE.Interop.IOleParentUndoUnit.Typ'Class;
      fCommit : Integer) return Integer is abstract;
   procedure DiscardFrom
     (This : access Typ;
      pUU : access Microsoft.VisualStudio.OLE.Interop.IOleUndoUnit.Typ'Class) is abstract;
   procedure Enable
     (This : access Typ;
      fEnable : Integer) is abstract;
   procedure EnumRedoable
     (This : access Typ;
      ppEnum : access Microsoft.VisualStudio.OLE.Interop.IEnumOleUndoUnits.Ref) is abstract;
   procedure EnumUndoable
     (This : access Typ;
      ppEnum : access Microsoft.VisualStudio.OLE.Interop.IEnumOleUndoUnits.Ref) is abstract;
   procedure GetLastRedoDescription
     (This : access Typ;
      pBstr : access MSSyst.String.Ref) is abstract;
   procedure GetLastUndoDescription
     (This : access Typ;
      pBstr : access MSSyst.String.Ref) is abstract;
   function GetOpenParentState
     (This : access Typ;
      pdwState : CIL_Types.Unsigned_Integer_addrof) return Integer is abstract;
   procedure Open
     (This : access Typ;
      pPUU : access Microsoft.VisualStudio.OLE.Interop.IOleParentUndoUnit.Typ'Class) is abstract;
   procedure RedoTo
     (This : access Typ;
      pUU : access Microsoft.VisualStudio.OLE.Interop.IOleUndoUnit.Typ'Class) is abstract;
   procedure UndoTo
     (This : access Typ;
      pUU : access Microsoft.VisualStudio.OLE.Interop.IOleUndoUnit.Typ'Class) is abstract;
private
   pragma Import (CIL, Add, "Add");
   pragma Import (CIL, Close, "Close");
   pragma Import (CIL, DiscardFrom, "DiscardFrom");
   pragma Import (CIL, Enable, "Enable");
   pragma Import (CIL, EnumRedoable, "EnumRedoable");
   pragma Import (CIL, EnumUndoable, "EnumUndoable");
   pragma Import (CIL, GetLastRedoDescription, "GetLastRedoDescription");
   pragma Import (CIL, GetLastUndoDescription, "GetLastUndoDescription");
   pragma Import (CIL, GetOpenParentState, "GetOpenParentState");
   pragma Import (CIL, Open, "Open");
   pragma Import (CIL, RedoTo, "RedoTo");
   pragma Import (CIL, UndoTo, "UndoTo");
end Microsoft.VisualStudio.OLE.Interop.IOleUndoManager;
pragma Import (CIL, Microsoft.VisualStudio.OLE.Interop.IOleUndoManager,
   ".ver 7:1:40304:0 .publickeytoken=( b0 3f 5f 7f 11 d5 0a 3a )",
   "[Microsoft.VisualStudio.OLE.Interop]Microsoft.VisualStudio.OLE.Interop.IOleUndoManager");
