-- Autogenerated by CIL2Ada v. 2
with MSSyst.Object;
with CIL_Types;
use CIL_Types;
with Microsoft.VisualStudio.OLE.Interop.FILETIME;
limited with Microsoft.VisualStudio.OLE.Interop.IBindCtx;
limited with Microsoft.VisualStudio.OLE.Interop.IEnumMoniker;
with Microsoft.VisualStudio.OLE.Interop.IPersist;
with Microsoft.VisualStudio.OLE.Interop.IPersistStream;
limited with Microsoft.VisualStudio.OLE.Interop.IStream;
with Microsoft.VisualStudio.OLE.Interop.ULARGE_INTEGER;
with MSSyst.Guid;
limited with MSSyst.String;
package Microsoft.VisualStudio.OLE.Interop.IMoniker is
   type Typ is interface;
   type Ref is access all Typ'Class;
   type Ref_addrof is access all Ref;
   type Ref_Arr is array (Natural range <>) of Ref;
   type Ref_Array is access all Ref_Arr;
   type Ref_Array_addrof is access all Ref_Array;
   procedure BindToObject
     (This : access Typ;
      pbc : access Microsoft.VisualStudio.OLE.Interop.IBindCtx.Typ'Class;
      pmkToLeft : access Microsoft.VisualStudio.OLE.Interop.IMoniker.Typ'Class;
      riidResult : access MSSyst.Guid.Valuetype;
      ppvResult : access MSSyst.Object.Ref) is abstract;
   procedure BindToStorage
     (This : access Typ;
      pbc : access Microsoft.VisualStudio.OLE.Interop.IBindCtx.Typ'Class;
      pmkToLeft : access Microsoft.VisualStudio.OLE.Interop.IMoniker.Typ'Class;
      riid : access MSSyst.Guid.Valuetype;
      ppvObj : access MSSyst.Object.Ref) is abstract;
   procedure CommonPrefixWith
     (This : access Typ;
      pmkOther : access Microsoft.VisualStudio.OLE.Interop.IMoniker.Typ'Class;
      ppmkPrefix : access Microsoft.VisualStudio.OLE.Interop.IMoniker.Ref) is abstract;
   procedure ComposeWith
     (This : access Typ;
      pmkRight : access Microsoft.VisualStudio.OLE.Interop.IMoniker.Typ'Class;
      fOnlyIfNotGeneric : Integer;
      ppmkComposite : access Microsoft.VisualStudio.OLE.Interop.IMoniker.Ref) is abstract;
   procedure Enum
     (This : access Typ;
      fForward : Integer;
      ppenumMoniker : access Microsoft.VisualStudio.OLE.Interop.IEnumMoniker.Ref) is abstract;
   function GetClassID
     (This : access Typ;
      pClassID : access MSSyst.Guid.Valuetype) return Integer is abstract;
   procedure GetDisplayName
     (This : access Typ;
      pbc : access Microsoft.VisualStudio.OLE.Interop.IBindCtx.Typ'Class;
      pmkToLeft : access Microsoft.VisualStudio.OLE.Interop.IMoniker.Typ'Class;
      ppszDisplayName : access MSSyst.String.Ref) is abstract;
   procedure GetSizeMax
     (This : access Typ;
      pcbSize : access Microsoft.VisualStudio.OLE.Interop.ULARGE_INTEGER.Valuetype_arr) is abstract;
   procedure GetTimeOfLastChange
     (This : access Typ;
      pbc : access Microsoft.VisualStudio.OLE.Interop.IBindCtx.Typ'Class;
      pmkToLeft : access Microsoft.VisualStudio.OLE.Interop.IMoniker.Typ'Class;
      pFileTime : access Microsoft.VisualStudio.OLE.Interop.FILETIME.Valuetype_arr) is abstract;
   procedure Hash
     (This : access Typ;
      pdwHash : CIL_Types.Unsigned_Integer_addrof) is abstract;
   procedure Inverse
     (This : access Typ;
      ppmk : access Microsoft.VisualStudio.OLE.Interop.IMoniker.Ref) is abstract;
   function IsDirty
     (This : access Typ) return Integer is abstract;
   procedure IsEqual
     (This : access Typ;
      pmkOtherMoniker : access Microsoft.VisualStudio.OLE.Interop.IMoniker.Typ'Class) is abstract;
   function IsRunning
     (This : access Typ;
      pbc : access Microsoft.VisualStudio.OLE.Interop.IBindCtx.Typ'Class;
      pmkToLeft : access Microsoft.VisualStudio.OLE.Interop.IMoniker.Typ'Class;
      pmkNewlyRunning : access Microsoft.VisualStudio.OLE.Interop.IMoniker.Typ'Class) return Integer is abstract;
   procedure IsSystemMoniker
     (This : access Typ;
      pdwMksys : CIL_Types.Unsigned_Integer_addrof) is abstract;
   procedure Load
     (This : access Typ;
      pstm : access Microsoft.VisualStudio.OLE.Interop.IStream.Typ'Class) is abstract;
   procedure ParseDisplayName
     (This : access Typ;
      pbc : access Microsoft.VisualStudio.OLE.Interop.IBindCtx.Typ'Class;
      pmkToLeft : access Microsoft.VisualStudio.OLE.Interop.IMoniker.Typ'Class;
      pszDisplayName : access MSSyst.String.Typ'Class;
      pchEaten : CIL_Types.Unsigned_Integer_addrof;
      ppmkOut : access Microsoft.VisualStudio.OLE.Interop.IMoniker.Ref) is abstract;
   procedure Reduce
     (This : access Typ;
      pbc : access Microsoft.VisualStudio.OLE.Interop.IBindCtx.Typ'Class;
      dwReduceHowFar : CIL_Types.Unsigned_Integer;
      ppmkToLeft : access Microsoft.VisualStudio.OLE.Interop.IMoniker.Ref;
      ppmkReduced : access Microsoft.VisualStudio.OLE.Interop.IMoniker.Ref) is abstract;
   procedure RelativePathTo
     (This : access Typ;
      pmkOther : access Microsoft.VisualStudio.OLE.Interop.IMoniker.Typ'Class;
      ppmkRelPath : access Microsoft.VisualStudio.OLE.Interop.IMoniker.Ref) is abstract;
   procedure Save
     (This : access Typ;
      pstm : access Microsoft.VisualStudio.OLE.Interop.IStream.Typ'Class;
      fClearDirty : Integer) is abstract;
private
   pragma Import (CIL, BindToObject, "BindToObject");
   pragma Import (CIL, BindToStorage, "BindToStorage");
   pragma Import (CIL, CommonPrefixWith, "CommonPrefixWith");
   pragma Import (CIL, ComposeWith, "ComposeWith");
   pragma Import (CIL, Enum, "Enum");
   pragma Import (CIL, GetClassID, "GetClassID");
   pragma Import (CIL, GetDisplayName, "GetDisplayName");
   pragma Import (CIL, GetSizeMax, "GetSizeMax");
   pragma Import (CIL, GetTimeOfLastChange, "GetTimeOfLastChange");
   pragma Import (CIL, Hash, "Hash");
   pragma Import (CIL, Inverse, "Inverse");
   pragma Import (CIL, IsDirty, "IsDirty");
   pragma Import (CIL, IsEqual, "IsEqual");
   pragma Import (CIL, IsRunning, "IsRunning");
   pragma Import (CIL, IsSystemMoniker, "IsSystemMoniker");
   pragma Import (CIL, Load, "Load");
   pragma Import (CIL, ParseDisplayName, "ParseDisplayName");
   pragma Import (CIL, Reduce, "Reduce");
   pragma Import (CIL, RelativePathTo, "RelativePathTo");
   pragma Import (CIL, Save, "Save");
end Microsoft.VisualStudio.OLE.Interop.IMoniker;
pragma Import (CIL, Microsoft.VisualStudio.OLE.Interop.IMoniker,
   ".ver 7:1:40304:0 .publickeytoken=( b0 3f 5f 7f 11 d5 0a 3a )",
   "[Microsoft.VisualStudio.OLE.Interop]Microsoft.VisualStudio.OLE.Interop.IMoniker");
