-- Autogenerated by CIL2Ada v. 2
with MSSyst.Object;
with CIL_Types;
use CIL_Types;
with Microsoft.VisualStudio.OLE.Interop.IPersist;
limited with Microsoft.VisualStudio.OLE.Interop.IStream;
with Microsoft.VisualStudio.OLE.Interop.ULARGE_INTEGER;
with MSSyst.Guid;
package Microsoft.VisualStudio.OLE.Interop.IPersistStream is
   type Typ is interface;
   type Ref is access all Typ'Class;
   type Ref_addrof is access all Ref;
   type Ref_Arr is array (Natural range <>) of Ref;
   type Ref_Array is access all Ref_Arr;
   type Ref_Array_addrof is access all Ref_Array;
   function GetClassID
     (This : access Typ;
      pClassID : access MSSyst.Guid.Valuetype) return Integer is abstract;
   procedure GetSizeMax
     (This : access Typ;
      pcbSize : access Microsoft.VisualStudio.OLE.Interop.ULARGE_INTEGER.Valuetype_arr) is abstract;
   function IsDirty
     (This : access Typ) return Integer is abstract;
   procedure Load
     (This : access Typ;
      pstm : access Microsoft.VisualStudio.OLE.Interop.IStream.Typ'Class) is abstract;
   procedure Save
     (This : access Typ;
      pstm : access Microsoft.VisualStudio.OLE.Interop.IStream.Typ'Class;
      fClearDirty : Integer) is abstract;
private
   pragma Import (CIL, GetClassID, "GetClassID");
   pragma Import (CIL, GetSizeMax, "GetSizeMax");
   pragma Import (CIL, IsDirty, "IsDirty");
   pragma Import (CIL, Load, "Load");
   pragma Import (CIL, Save, "Save");
end Microsoft.VisualStudio.OLE.Interop.IPersistStream;
pragma Import (CIL, Microsoft.VisualStudio.OLE.Interop.IPersistStream,
   ".ver 7:1:40304:0 .publickeytoken=( b0 3f 5f 7f 11 d5 0a 3a )",
   "[Microsoft.VisualStudio.OLE.Interop]Microsoft.VisualStudio.OLE.Interop.IPersistStream");
