-- Autogenerated by CIL2Ada v. 2
with MSSyst.Object;
with CIL_Types;
use CIL_Types;
limited with Microsoft.VisualStudio.OLE.Interop.IConnectionPoint;
limited with Microsoft.VisualStudio.OLE.Interop.IEnumConnectionPoints;
with MSSyst.Guid;
package Microsoft.VisualStudio.OLE.Interop.IConnectionPointContainer is
   type Typ is interface;
   type Ref is access all Typ'Class;
   type Ref_addrof is access all Ref;
   type Ref_Arr is array (Natural range <>) of Ref;
   type Ref_Array is access all Ref_Arr;
   type Ref_Array_addrof is access all Ref_Array;
   procedure EnumConnectionPoints
     (This : access Typ;
      ppEnum : access Microsoft.VisualStudio.OLE.Interop.IEnumConnectionPoints.Ref) is abstract;
   procedure FindConnectionPoint
     (This : access Typ;
      riid : access MSSyst.Guid.Valuetype;
      ppCP : access Microsoft.VisualStudio.OLE.Interop.IConnectionPoint.Ref) is abstract;
private
   pragma Import (CIL, EnumConnectionPoints, "EnumConnectionPoints");
   pragma Import (CIL, FindConnectionPoint, "FindConnectionPoint");
end Microsoft.VisualStudio.OLE.Interop.IConnectionPointContainer;
pragma Import (CIL, Microsoft.VisualStudio.OLE.Interop.IConnectionPointContainer,
   ".ver 7:1:40304:0 .publickeytoken=( b0 3f 5f 7f 11 d5 0a 3a )",
   "[Microsoft.VisualStudio.OLE.Interop]Microsoft.VisualStudio.OLE.Interop.IConnectionPointContainer");
