-- Autogenerated by CIL2Ada v. 2
with MSSyst.Object;
with CIL_Types;
use CIL_Types;
limited with Microsoft.VisualStudio.Package_k.Methods;
with Microsoft.VisualStudio.TextManager.Interop.IVsMethodData;
limited with Microsoft.VisualStudio.TextManager.Interop.IVsTextView;
limited with Microsoft.VisualStudio.TextManager.Interop.MethodTextType;
limited with Microsoft.VisualStudio.TextManager.Interop.ParameterTextType;
limited with Microsoft.VisualStudio.TextManager.Interop.TextSpan;
with MSSyst.IDisposable;
limited with MSSyst.IServiceProvider;
limited with MSSyst.String;
limited with MSSyst.Type_k;
package Microsoft.VisualStudio.Package_k.MethodData is
   type Typ is new MSSyst.Object.Typ
         and Microsoft.VisualStudio.TextManager.Interop.IVsMethodData.Typ
         and MSSyst.IDisposable.Typ
   with record
      null;
   end record;
   type Ref is access all Typ'Class;
   type Ref_addrof is access all Ref;
   type Ref_Arr is array (Natural range <>) of Ref;
   type Ref_Array is access all Ref_Arr;
   type Ref_Array_addrof is access all Ref_Array;
   function new_MethodData
     (This : Ref := null;
      site : access MSSyst.IServiceProvider.Typ'Class) return Ref;
   procedure AdjustCurrentParameter
     (This : access Typ;
      increment : Integer);
   procedure Close
     (This : access Typ);
   procedure Dismiss
     (This : access Typ);
   procedure Dispose
     (This : access Typ);
   function get_IsDisplayed
     (This : access Typ) return Standard.Boolean;
   function GetContextStream
     (This : access Typ;
      pos : CIL_Types.Int32_addrof;
      length : CIL_Types.Int32_addrof) return Integer;
   function GetCurMethod
     (This : access Typ) return Integer;
   function GetCurrentParameter
     (This : access Typ;
      method : Integer) return Integer;
   function GetMethodText
     (This : access Typ;
      method : Integer;
      type_k : Microsoft.VisualStudio.TextManager.Interop.MethodTextType.Valuetype) return CIL_Types.native_int;
   function GetOverloadCount
     (This : access Typ) return Integer;
   function GetParameterCount
     (This : access Typ;
      method : Integer) return Integer;
   function GetParameterText
     (This : access Typ;
      method : Integer;
      parameter : Integer;
      type_k : Microsoft.VisualStudio.TextManager.Interop.ParameterTextType.Valuetype) return CIL_Types.native_int;
   function NextMethod
     (This : access Typ) return Integer;
   procedure OnDismiss
     (This : access Typ);
   function PrevMethod
     (This : access Typ) return Integer;
   procedure Refresh
     (This : access Typ;
      textView : access Microsoft.VisualStudio.TextManager.Interop.IVsTextView.Typ'Class;
      methods : access Microsoft.VisualStudio.Package_k.Methods.Typ'Class;
      currentParameter : Integer;
      context : Microsoft.VisualStudio.TextManager.Interop.TextSpan.Valuetype);
   procedure UpdateView
     (This : access Typ);
private
   pragma Convention (CIL, Typ);
   pragma Cil_Constructor (new_MethodData);
   pragma Import (CIL, AdjustCurrentParameter, "AdjustCurrentParameter");
   pragma Import (CIL, Close, "Close");
   pragma Import (CIL, Dismiss, "Dismiss");
   pragma Import (CIL, Dispose, "Dispose");
   pragma Import (CIL, get_IsDisplayed, "get_IsDisplayed");
   pragma Import (CIL, GetContextStream, "GetContextStream");
   pragma Import (CIL, GetCurMethod, "GetCurMethod");
   pragma Import (CIL, GetCurrentParameter, "GetCurrentParameter");
   pragma Import (CIL, GetMethodText, "GetMethodText");
   pragma Import (CIL, GetOverloadCount, "GetOverloadCount");
   pragma Import (CIL, GetParameterCount, "GetParameterCount");
   pragma Import (CIL, GetParameterText, "GetParameterText");
   pragma Import (CIL, NextMethod, "NextMethod");
   pragma Import (CIL, OnDismiss, "OnDismiss");
   pragma Import (CIL, PrevMethod, "PrevMethod");
   pragma Import (CIL, Refresh, "Refresh");
   pragma Import (CIL, UpdateView, "UpdateView");
end Microsoft.VisualStudio.Package_k.MethodData;
pragma Import (CIL, Microsoft.VisualStudio.Package_k.MethodData,
   ".ver 2:0:0:0 .publickeytoken=( b0 3f 5f 7f 11 d5 0a 3a )",
   "[Microsoft.VisualStudio.Package.LanguageService]Microsoft.VisualStudio.Package.MethodData");
