-- Autogenerated by CIL2Ada v. 2
with MSSyst.Object;
with CIL_Types;
use CIL_Types;
limited with Microsoft.VisualStudio.OLE.Interop.IDataObject;
limited with Microsoft.VisualStudio.OLE.Interop.IOleCommandTarget;
with Microsoft.VisualStudio.OLE.Interop.POINT;
with Microsoft.VisualStudio.TextManager.Interop.INITVIEW;
limited with Microsoft.VisualStudio.TextManager.Interop.IVsCompletionSet;
limited with Microsoft.VisualStudio.TextManager.Interop.IVsTextLines;
limited with Microsoft.VisualStudio.TextManager.Interop.IVsTipWindow;
limited with Microsoft.VisualStudio.TextManager.Interop.IVsViewRangeClient;
limited with Microsoft.VisualStudio.TextManager.Interop.TextSelMode;
with Microsoft.VisualStudio.TextManager.Interop.TextSpan;
limited with MSSyst.String;
package Microsoft.VisualStudio.TextManager.Interop.IVsTextView is
   type Typ is interface;
   type Ref is access all Typ'Class;
   type Ref_addrof is access all Ref;
   type Ref_Arr is array (Natural range <>) of Ref;
   type Ref_Array is access all Ref_Arr;
   type Ref_Array_addrof is access all Ref_Array;
   function AddCommandFilter
     (This : access Typ;
      pNewCmdTarg : access Microsoft.VisualStudio.OLE.Interop.IOleCommandTarget.Typ'Class;
      ppNextCmdTarg : access Microsoft.VisualStudio.OLE.Interop.IOleCommandTarget.Ref) return Integer is abstract;
   function CenterColumns
     (This : access Typ;
      iLine : Integer;
      iLeftCol : Integer;
      iColCount : Integer) return Integer is abstract;
   function CenterLines
     (This : access Typ;
      iTopLine : Integer;
      iCount : Integer) return Integer is abstract;
   function ClearSelection
     (This : access Typ;
      fMoveToAnchor : Integer) return Integer is abstract;
   function CloseView
     (This : access Typ) return Integer is abstract;
   function EnsureSpanVisible
     (This : access Typ;
      span : Microsoft.VisualStudio.TextManager.Interop.TextSpan.Valuetype) return Integer is abstract;
   function GetBuffer
     (This : access Typ;
      ppBuffer : access Microsoft.VisualStudio.TextManager.Interop.IVsTextLines.Ref) return Integer is abstract;
   function GetCaretPos
     (This : access Typ;
      piLine : CIL_Types.Int32_addrof;
      piColumn : CIL_Types.Int32_addrof) return Integer is abstract;
   function GetLineAndColumn
     (This : access Typ;
      iPos : Integer;
      piLine : CIL_Types.Int32_addrof;
      piIndex : CIL_Types.Int32_addrof) return Integer is abstract;
   function GetLineHeight
     (This : access Typ;
      piLineHeight : CIL_Types.Int32_addrof) return Integer is abstract;
   function GetNearestPosition
     (This : access Typ;
      iLine : Integer;
      iCol : Integer;
      piPos : CIL_Types.Int32_addrof;
      piVirtualSpaces : CIL_Types.Int32_addrof) return Integer is abstract;
   function GetPointOfLineColumn
     (This : access Typ;
      iLine : Integer;
      iCol : Integer;
      ppt : access Microsoft.VisualStudio.OLE.Interop.POINT.Valuetype_arr) return Integer is abstract;
   function GetScrollInfo
     (This : access Typ;
      iBar : Integer;
      piMinUnit : CIL_Types.Int32_addrof;
      piMaxUnit : CIL_Types.Int32_addrof;
      piVisibleUnits : CIL_Types.Int32_addrof;
      piFirstVisibleUnit : CIL_Types.Int32_addrof) return Integer is abstract;
   function GetSelectedText
     (This : access Typ;
      pbstrText : access MSSyst.String.Ref) return Integer is abstract;
   function GetSelection
     (This : access Typ;
      piAnchorLine : CIL_Types.Int32_addrof;
      piAnchorCol : CIL_Types.Int32_addrof;
      piEndLine : CIL_Types.Int32_addrof;
      piEndCol : CIL_Types.Int32_addrof) return Integer is abstract;
   function GetSelectionDataObject
     (This : access Typ;
      ppIDataObject : access Microsoft.VisualStudio.OLE.Interop.IDataObject.Ref) return Integer is abstract;
   function GetSelectionMode
     (This : access Typ) return Microsoft.VisualStudio.TextManager.Interop.TextSelMode.Valuetype is abstract;
   function GetSelectionSpan
     (This : access Typ;
      pSpan : access Microsoft.VisualStudio.TextManager.Interop.TextSpan.Valuetype_arr) return Integer is abstract;
   function GetTextStream
     (This : access Typ;
      iTopLine : Integer;
      iTopCol : Integer;
      iBottomLine : Integer;
      iBottomCol : Integer;
      pbstrText : access MSSyst.String.Ref) return Integer is abstract;
   function GetWindowHandle
     (This : access Typ) return CIL_Types.native_int is abstract;
   function GetWordExtent
     (This : access Typ;
      iLine : Integer;
      iCol : Integer;
      dwFlags : CIL_Types.Unsigned_Integer;
      pSpan : access Microsoft.VisualStudio.TextManager.Interop.TextSpan.Valuetype_arr) return Integer is abstract;
   function HighlightMatchingBrace
     (This : access Typ;
      dwFlags : CIL_Types.Unsigned_Integer;
      cSpans : CIL_Types.Unsigned_Integer;
      rgBaseSpans : access Microsoft.VisualStudio.TextManager.Interop.TextSpan.Valuetype_arr) return Integer is abstract;
   function Initialize
     (This : access Typ;
      pBuffer : access Microsoft.VisualStudio.TextManager.Interop.IVsTextLines.Typ'Class;
      hwndParent : CIL_Types.native_int;
      InitFlags : CIL_Types.Unsigned_Integer;
      pInitView : access Microsoft.VisualStudio.TextManager.Interop.INITVIEW.Valuetype_arr) return Integer is abstract;
   function PositionCaretForEditing
     (This : access Typ;
      iLine : Integer;
      cIndentLevels : Integer) return Integer is abstract;
   function RemoveCommandFilter
     (This : access Typ;
      pCmdTarg : access Microsoft.VisualStudio.OLE.Interop.IOleCommandTarget.Typ'Class) return Integer is abstract;
   function ReplaceTextOnLine
     (This : access Typ;
      iLine : Integer;
      iStartCol : Integer;
      iCharsToReplace : Integer;
      pszNewText : access MSSyst.String.Typ'Class;
      iNewLen : Integer) return Integer is abstract;
   function RestrictViewRange
     (This : access Typ;
      iMinLine : Integer;
      iMaxLine : Integer;
      pClient : access Microsoft.VisualStudio.TextManager.Interop.IVsViewRangeClient.Typ'Class) return Integer is abstract;
   function SendExplicitFocus
     (This : access Typ) return Integer is abstract;
   function SetBuffer
     (This : access Typ;
      pBuffer : access Microsoft.VisualStudio.TextManager.Interop.IVsTextLines.Typ'Class) return Integer is abstract;
   function SetCaretPos
     (This : access Typ;
      iLine : Integer;
      iColumn : Integer) return Integer is abstract;
   function SetScrollPosition
     (This : access Typ;
      iBar : Integer;
      iFirstVisibleUnit : Integer) return Integer is abstract;
   function SetSelection
     (This : access Typ;
      iAnchorLine : Integer;
      iAnchorCol : Integer;
      iEndLine : Integer;
      iEndCol : Integer) return Integer is abstract;
   function SetSelectionMode
     (This : access Typ;
      iSelMode : Microsoft.VisualStudio.TextManager.Interop.TextSelMode.Valuetype) return Integer is abstract;
   function SetTopLine
     (This : access Typ;
      iBaseLine : Integer) return Integer is abstract;
   function UpdateCompletionStatus
     (This : access Typ;
      pCompSet : access Microsoft.VisualStudio.TextManager.Interop.IVsCompletionSet.Typ'Class;
      dwFlags : CIL_Types.Unsigned_Integer) return Integer is abstract;
   function UpdateTipWindow
     (This : access Typ;
      pTipWindow : access Microsoft.VisualStudio.TextManager.Interop.IVsTipWindow.Typ'Class;
      dwFlags : CIL_Types.Unsigned_Integer) return Integer is abstract;
   function UpdateViewFrameCaption
     (This : access Typ) return Integer is abstract;
private
   pragma Import (CIL, AddCommandFilter, "AddCommandFilter");
   pragma Import (CIL, CenterColumns, "CenterColumns");
   pragma Import (CIL, CenterLines, "CenterLines");
   pragma Import (CIL, ClearSelection, "ClearSelection");
   pragma Import (CIL, CloseView, "CloseView");
   pragma Import (CIL, EnsureSpanVisible, "EnsureSpanVisible");
   pragma Import (CIL, GetBuffer, "GetBuffer");
   pragma Import (CIL, GetCaretPos, "GetCaretPos");
   pragma Import (CIL, GetLineAndColumn, "GetLineAndColumn");
   pragma Import (CIL, GetLineHeight, "GetLineHeight");
   pragma Import (CIL, GetNearestPosition, "GetNearestPosition");
   pragma Import (CIL, GetPointOfLineColumn, "GetPointOfLineColumn");
   pragma Import (CIL, GetScrollInfo, "GetScrollInfo");
   pragma Import (CIL, GetSelectedText, "GetSelectedText");
   pragma Import (CIL, GetSelection, "GetSelection");
   pragma Import (CIL, GetSelectionDataObject, "GetSelectionDataObject");
   pragma Import (CIL, GetSelectionMode, "GetSelectionMode");
   pragma Import (CIL, GetSelectionSpan, "GetSelectionSpan");
   pragma Import (CIL, GetTextStream, "GetTextStream");
   pragma Import (CIL, GetWindowHandle, "GetWindowHandle");
   pragma Import (CIL, GetWordExtent, "GetWordExtent");
   pragma Import (CIL, HighlightMatchingBrace, "HighlightMatchingBrace");
   pragma Import (CIL, Initialize, "Initialize");
   pragma Import (CIL, PositionCaretForEditing, "PositionCaretForEditing");
   pragma Import (CIL, RemoveCommandFilter, "RemoveCommandFilter");
   pragma Import (CIL, ReplaceTextOnLine, "ReplaceTextOnLine");
   pragma Import (CIL, RestrictViewRange, "RestrictViewRange");
   pragma Import (CIL, SendExplicitFocus, "SendExplicitFocus");
   pragma Import (CIL, SetBuffer, "SetBuffer");
   pragma Import (CIL, SetCaretPos, "SetCaretPos");
   pragma Import (CIL, SetScrollPosition, "SetScrollPosition");
   pragma Import (CIL, SetSelection, "SetSelection");
   pragma Import (CIL, SetSelectionMode, "SetSelectionMode");
   pragma Import (CIL, SetTopLine, "SetTopLine");
   pragma Import (CIL, UpdateCompletionStatus, "UpdateCompletionStatus");
   pragma Import (CIL, UpdateTipWindow, "UpdateTipWindow");
   pragma Import (CIL, UpdateViewFrameCaption, "UpdateViewFrameCaption");
end Microsoft.VisualStudio.TextManager.Interop.IVsTextView;
pragma Import (CIL, Microsoft.VisualStudio.TextManager.Interop.IVsTextView,
   ".ver 7:1:40304:0 .publickeytoken=( b0 3f 5f 7f 11 d5 0a 3a )",
   "[Microsoft.VisualStudio.TextManager.Interop]Microsoft.VisualStudio.TextManager.Interop.IVsTextView");
